[package]
name = "seekfs-bench"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Benchmark harness scaffolding for seekfs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
clap = { version = "4", features = ["derive"] }

