[package]
name = "seekfs-proto"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "HTTP/JSON types for seekfs Blob API, hints, advisor"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

